OrganizeImports {
  groups = [
    "re:javax?\\.",
    "scala.",
    "cats.",
    "fs2.",
    "io.circe.",
    "persistent4s.",
    "*",
  ]
  groupedImports       = Merge
  importSelectorsOrder = Ascii
  importsOrder         = Ascii
  removeUnused         = true
  targetDialect        = Scala3
}
